# Generated by Django 5.2.7 on 2025-10-10 18:13

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "booking_code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Código de reserva"
                    ),
                ),
                (
                    "number_of_participants",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Número de participantes",
                    ),
                ),
                (
                    "participants_info",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="Información de participantes",
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(
                        max_length=200, verbose_name="Contacto de emergencia"
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        max_length=20, verbose_name="Teléfono de emergencia"
                    ),
                ),
                (
                    "emergency_contact_relationship",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Relación"
                    ),
                ),
                (
                    "group_medical_notes",
                    models.TextField(blank=True, verbose_name="Notas médicas grupales"),
                ),
                (
                    "special_requirements",
                    models.TextField(
                        blank=True, verbose_name="Requerimientos especiales"
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio base"
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio total"
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Descuento aplicado",
                    ),
                ),
                (
                    "taxes_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Impuestos",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", max_length=3, verbose_name="Moneda"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente de pago"),
                            ("confirmed", "Confirmada"),
                            ("paid", "Pagada"),
                            ("cancelled", "Cancelada"),
                            ("refunded", "Reembolsada"),
                            ("completed", "Completada"),
                            ("no_show", "No presentado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "booking_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de reserva"
                    ),
                ),
                (
                    "confirmation_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de confirmación"
                    ),
                ),
                (
                    "payment_due_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha límite de pago"
                    ),
                ),
                (
                    "cancellation_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de cancelación"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Método de pago"
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Referencia de pago"
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("processing", "Procesando"),
                            ("completed", "Completado"),
                            ("failed", "Fallido"),
                            ("cancelled", "Cancelado"),
                            ("refunded", "Reembolsado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado de pago",
                    ),
                ),
                (
                    "special_requests",
                    models.TextField(blank=True, verbose_name="Solicitudes especiales"),
                ),
                (
                    "internal_notes",
                    models.TextField(blank=True, verbose_name="Notas internas"),
                ),
                (
                    "customer_notes",
                    models.TextField(blank=True, verbose_name="Notas del cliente"),
                ),
                (
                    "send_reminders",
                    models.BooleanField(
                        default=True, verbose_name="Enviar recordatorios"
                    ),
                ),
                (
                    "reminder_sent",
                    models.BooleanField(
                        default=False, verbose_name="Recordatorio enviado"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Reserva",
                "verbose_name_plural": "Reservas",
                "ordering": ["-booking_date"],
            },
        ),
        migrations.CreateModel(
            name="BookingDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("contract", "Contrato"),
                            ("invoice", "Factura"),
                            ("receipt", "Recibo"),
                            ("waiver", "Descargo de responsabilidad"),
                            ("insurance", "Seguro"),
                            ("itinerary", "Itinerario"),
                            ("confirmation", "Confirmación"),
                            ("other", "Otro"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de documento",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="booking_documents/", verbose_name="Archivo"
                    ),
                ),
                (
                    "file_size",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Tamaño del archivo"
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Tipo MIME"
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="Requerido"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Verificado"),
                ),
                (
                    "verification_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de verificación"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de expiración"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Documento de reserva",
                "verbose_name_plural": "Documentos de reserva",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BookingParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Apellido"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono"
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de nacimiento"
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nacionalidad"
                    ),
                ),
                (
                    "passport_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Número de pasaporte"
                    ),
                ),
                (
                    "passport_expiry",
                    models.DateField(
                        blank=True, null=True, verbose_name="Vencimiento de pasaporte"
                    ),
                ),
                (
                    "medical_conditions",
                    models.TextField(blank=True, verbose_name="Condiciones médicas"),
                ),
                ("allergies", models.TextField(blank=True, verbose_name="Alergias")),
                (
                    "medications",
                    models.TextField(blank=True, verbose_name="Medicamentos"),
                ),
                (
                    "dietary_restrictions",
                    models.TextField(
                        blank=True, verbose_name="Restricciones alimentarias"
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Contacto de emergencia",
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono de emergencia"
                    ),
                ),
                (
                    "emergency_contact_relationship",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Relación"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmado"),
                            ("pending", "Pendiente"),
                            ("cancelled", "Cancelado"),
                            ("waitlist", "Lista de espera"),
                        ],
                        default="confirmed",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "special_requests",
                    models.TextField(blank=True, verbose_name="Solicitudes especiales"),
                ),
                (
                    "room_preference",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Preferencia de habitación",
                    ),
                ),
                (
                    "seat_preference",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Preferencia de asiento"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Participante de reserva",
                "verbose_name_plural": "Participantes de reserva",
            },
        ),
        migrations.CreateModel(
            name="BookingPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Monto"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", max_length=3, verbose_name="Moneda"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(max_length=50, verbose_name="Método de pago"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("processing", "Procesando"),
                            ("completed", "Completado"),
                            ("failed", "Fallido"),
                            ("cancelled", "Cancelado"),
                            ("refunded", "Reembolsado"),
                            ("partially_refunded", "Parcialmente reembolsado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID de transacción"
                    ),
                ),
                (
                    "payment_gateway",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Pasarela de pago"
                    ),
                ),
                (
                    "gateway_response",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Respuesta de la pasarela",
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de pago"
                    ),
                ),
                (
                    "processed_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de procesamiento"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "failure_reason",
                    models.TextField(blank=True, verbose_name="Razón de fallo"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Pago de reserva",
                "verbose_name_plural": "Pagos de reserva",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BookingReminder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("payment_due", "Vencimiento de pago"),
                            ("departure", "Fecha de salida"),
                            ("document_required", "Documento requerido"),
                            ("preparation", "Preparación para el viaje"),
                            ("feedback", "Solicitud de feedback"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de recordatorio",
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateTimeField(verbose_name="Fecha programada"),
                ),
                (
                    "sent_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de envío"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Programado"),
                            ("sent", "Enviado"),
                            ("cancelled", "Cancelado"),
                            ("failed", "Fallido"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "subject",
                    models.CharField(blank=True, max_length=200, verbose_name="Asunto"),
                ),
                ("message", models.TextField(blank=True, verbose_name="Mensaje")),
                (
                    "send_email",
                    models.BooleanField(default=True, verbose_name="Enviar por email"),
                ),
                (
                    "send_sms",
                    models.BooleanField(default=False, verbose_name="Enviar por SMS"),
                ),
                (
                    "send_push",
                    models.BooleanField(default=False, verbose_name="Enviar push"),
                ),
                (
                    "recipient_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        verbose_name="Email del destinatario",
                    ),
                ),
                (
                    "recipient_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Teléfono del destinatario",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Recordatorio de reserva",
                "verbose_name_plural": "Recordatorios de reserva",
                "ordering": ["scheduled_date"],
            },
        ),
    ]
