# Generated by Django 5.2.7 on 2025-10-10 18:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Media360Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Ubicación"
                    ),
                ),
                (
                    "coordinates",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Coordenadas GPS"
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("single_panorama", "Panorama único"),
                            ("virtual_tour", "Tour virtual"),
                            ("drone_360", "Drone 360°"),
                            ("underwater_360", "Subacuático 360°"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de proyecto",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Procesando"),
                            ("ready", "Listo"),
                            ("published", "Publicado"),
                            ("draft", "Borrador"),
                            ("error", "Error"),
                        ],
                        default="processing",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "initial_view",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Vista inicial"
                    ),
                ),
                (
                    "hotspots",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Puntos de interés"
                    ),
                ),
                (
                    "navigation",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Navegación"
                    ),
                ),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="360/previews/",
                        verbose_name="Imagen de preview",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="360/thumbnails/",
                        verbose_name="Miniatura",
                    ),
                ),
                (
                    "view_count",
                    models.IntegerField(default=0, verbose_name="Número de vistas"),
                ),
                (
                    "average_view_time",
                    models.IntegerField(
                        default=0, verbose_name="Tiempo promedio de vista"
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Público"),
                            ("private", "Privado"),
                            ("password", "Protegido por contraseña"),
                        ],
                        default="public",
                        max_length=20,
                        verbose_name="Visibilidad",
                    ),
                ),
                (
                    "access_password",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Contraseña de acceso"
                    ),
                ),
                (
                    "camera_info",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Información de cámara"
                    ),
                ),
                (
                    "processing_info",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Información de procesamiento",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Proyecto 360°",
                "verbose_name_plural": "Proyectos 360°",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Media360Scene",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "panorama_file",
                    models.FileField(
                        upload_to="360/panoramas/", verbose_name="Archivo panorámico"
                    ),
                ),
                (
                    "preview_file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="360/previews/",
                        verbose_name="Preview",
                    ),
                ),
                (
                    "initial_yaw",
                    models.FloatField(default=0, verbose_name="Yaw inicial"),
                ),
                (
                    "initial_pitch",
                    models.FloatField(default=0, verbose_name="Pitch inicial"),
                ),
                (
                    "initial_fov",
                    models.FloatField(default=75, verbose_name="FOV inicial"),
                ),
                ("width", models.IntegerField(verbose_name="Ancho")),
                ("height", models.IntegerField(verbose_name="Alto")),
                ("file_size", models.IntegerField(verbose_name="Tamaño del archivo")),
                (
                    "is_processed",
                    models.BooleanField(default=False, verbose_name="Procesado"),
                ),
                (
                    "processing_error",
                    models.TextField(blank=True, verbose_name="Error de procesamiento"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Orden")),
                (
                    "hotspots",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Puntos de interés"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Escena 360°",
                "verbose_name_plural": "Escenas 360°",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="MediaAlbum",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "event_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha del evento"
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Público"),
                            ("private", "Privado"),
                            ("password", "Protegido por contraseña"),
                            ("users_only", "Solo usuarios registrados"),
                        ],
                        default="public",
                        max_length=20,
                        verbose_name="Visibilidad",
                    ),
                ),
                (
                    "access_password",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Contraseña de acceso"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("tour", "Tour"),
                            ("event", "Evento"),
                            ("destination", "Destino"),
                            ("wildlife", "Vida silvestre"),
                            ("culture", "Cultura"),
                            ("adventure", "Aventura"),
                            ("other", "Otro"),
                        ],
                        max_length=50,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Etiquetas"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Ubicación"
                    ),
                ),
                (
                    "coordinates",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Coordenadas GPS"
                    ),
                ),
                (
                    "view_count",
                    models.IntegerField(default=0, verbose_name="Número de vistas"),
                ),
                (
                    "download_count",
                    models.IntegerField(default=0, verbose_name="Número de descargas"),
                ),
                (
                    "share_count",
                    models.IntegerField(
                        default=0, verbose_name="Número de compartidos"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Destacado"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=False, verbose_name="Requiere aprobación"
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=True, verbose_name="Aprobado"),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="albums/covers/",
                        verbose_name="Imagen de portada",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="albums/thumbnails/",
                        verbose_name="Miniatura",
                    ),
                ),
                (
                    "allow_downloads",
                    models.BooleanField(
                        default=True, verbose_name="Permitir descargas"
                    ),
                ),
                (
                    "allow_sharing",
                    models.BooleanField(
                        default=True, verbose_name="Permitir compartir"
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Orden")),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Título SEO"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(blank=True, verbose_name="Descripción SEO"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Álbum de medios",
                "verbose_name_plural": "Álbumes de medios",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MediaCollection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "collection_type",
                    models.CharField(
                        choices=[
                            ("featured", "Destacados"),
                            ("recent", "Recientes"),
                            ("popular", "Populares"),
                            ("category", "Por categoría"),
                            ("location", "Por ubicación"),
                            ("seasonal", "Estacional"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de colección",
                    ),
                ),
                (
                    "filters",
                    models.JSONField(blank=True, default=dict, verbose_name="Filtros"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Orden")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "is_automatic",
                    models.BooleanField(default=False, verbose_name="Automático"),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de inicio"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de fin"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Colección de medios",
                "verbose_name_plural": "Colecciones de medios",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Texto alternativo"
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="media/files/", verbose_name="Archivo"),
                ),
                (
                    "file_type",
                    models.CharField(max_length=50, verbose_name="Tipo de archivo"),
                ),
                ("file_size", models.IntegerField(verbose_name="Tamaño del archivo")),
                (
                    "mime_type",
                    models.CharField(max_length=100, verbose_name="Tipo MIME"),
                ),
                (
                    "width",
                    models.IntegerField(blank=True, null=True, verbose_name="Ancho"),
                ),
                (
                    "height",
                    models.IntegerField(blank=True, null=True, verbose_name="Alto"),
                ),
                (
                    "duration",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Duración (segundos)"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="media/thumbnails/",
                        verbose_name="Miniatura",
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(default=False, verbose_name="Procesado"),
                ),
                (
                    "processing_error",
                    models.TextField(blank=True, verbose_name="Error de procesamiento"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Destacado"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Orden")),
                (
                    "is_cover",
                    models.BooleanField(default=False, verbose_name="Es portada"),
                ),
                (
                    "view_count",
                    models.IntegerField(default=0, verbose_name="Número de vistas"),
                ),
                (
                    "download_count",
                    models.IntegerField(default=0, verbose_name="Número de descargas"),
                ),
                (
                    "allow_download",
                    models.BooleanField(default=True, verbose_name="Permitir descarga"),
                ),
                (
                    "requires_auth",
                    models.BooleanField(
                        default=False, verbose_name="Requiere autenticación"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Archivo de medios",
                "verbose_name_plural": "Archivos de medios",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="MediaView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID de sesión"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Dirección IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, verbose_name="Agente de usuario"),
                ),
                ("referrer", models.URLField(blank=True, verbose_name="Referrer")),
                (
                    "view_duration",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Duración de la vista"
                    ),
                ),
                (
                    "country",
                    models.CharField(blank=True, max_length=100, verbose_name="País"),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Ciudad"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Vista de medios",
                "verbose_name_plural": "Vistas de medios",
                "ordering": ["-created_at"],
            },
        ),
    ]
