# Generated by Django 5.2.7 on 2025-10-10 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0002_initial"),
        ("media_manager", "0001_initial"),
        ("tours", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="media360project",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_360_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="media360project",
            name="tour",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects_360",
                to="tours.tour",
            ),
        ),
        migrations.AddField(
            model_name="media360project",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_360_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="media360scene",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scenes",
                to="media_manager.media360project",
            ),
        ),
        migrations.AddField(
            model_name="mediaalbum",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="albums",
                to="bookings.booking",
            ),
        ),
        migrations.AddField(
            model_name="mediaalbum",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_albums",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mediaalbum",
            name="tour",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="albums",
                to="tours.tour",
            ),
        ),
        migrations.AddField(
            model_name="mediaalbum",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_albums",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="media360project",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects_360",
                to="media_manager.mediaalbum",
            ),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="album",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="media_manager.mediaalbum",
            ),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="uploaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_files",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mediaview",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="views",
                to="media_manager.mediaalbum",
            ),
        ),
        migrations.AddField(
            model_name="mediaview",
            name="media_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="views",
                to="media_manager.mediafile",
            ),
        ),
        migrations.AddField(
            model_name="mediaview",
            name="project_360",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="views",
                to="media_manager.media360project",
            ),
        ),
        migrations.AddField(
            model_name="mediaview",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="media_views",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="mediaalbum",
            index=models.Index(
                fields=["visibility", "is_active"],
                name="media_manag_visibil_be7f18_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mediaalbum",
            index=models.Index(
                fields=["tour", "is_active"], name="media_manag_tour_id_8346b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mediaalbum",
            index=models.Index(
                fields=["is_featured", "created_at"],
                name="media_manag_is_feat_a4b415_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mediaview",
            index=models.Index(
                fields=["created_at"], name="media_manag_created_9547f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mediaview",
            index=models.Index(
                fields=["media_file", "created_at"],
                name="media_manag_media_f_9be231_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mediaview",
            index=models.Index(
                fields=["user", "created_at"], name="media_manag_user_id_d2b4da_idx"
            ),
        ),
    ]
