# Generated by Django 5.2.7 on 2025-10-10 18:13

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tour",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Código"),
                ),
                (
                    "short_description",
                    models.TextField(max_length=500, verbose_name="Descripción corta"),
                ),
                (
                    "full_description",
                    models.TextField(verbose_name="Descripción completa"),
                ),
                (
                    "itinerary",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Itinerario"
                    ),
                ),
                (
                    "included_services",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Servicios incluidos"
                    ),
                ),
                (
                    "excluded_services",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Servicios excluidos"
                    ),
                ),
                (
                    "requirements",
                    models.TextField(blank=True, verbose_name="Requisitos"),
                ),
                (
                    "location",
                    models.CharField(max_length=200, verbose_name="Ubicación"),
                ),
                (
                    "coordinates",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Coordenadas GPS"
                    ),
                ),
                (
                    "duration_days",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Duración en días",
                    ),
                ),
                (
                    "duration_nights",
                    models.IntegerField(default=0, verbose_name="Noches"),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("easy", "Fácil"),
                            ("moderate", "Moderado"),
                            ("challenging", "Desafiante"),
                            ("extreme", "Extremo"),
                        ],
                        max_length=20,
                        verbose_name="Nivel de dificultad",
                    ),
                ),
                (
                    "physical_demand",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Demanda física",
                    ),
                ),
                (
                    "technical_demand",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Demanda técnica",
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio base"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", max_length=3, verbose_name="Moneda"
                    ),
                ),
                (
                    "min_participants",
                    models.IntegerField(
                        default=1, verbose_name="Mínimo de participantes"
                    ),
                ),
                (
                    "max_participants",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Máximo de participantes",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Fecha de inicio")),
                ("end_date", models.DateField(verbose_name="Fecha de fin")),
                (
                    "booking_deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha límite de reserva"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("published", "Publicado"),
                            ("cancelled", "Cancelado"),
                            ("completed", "Completado"),
                            ("suspended", "Suspendido"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Destacado"),
                ),
                (
                    "is_private",
                    models.BooleanField(default=False, verbose_name="Privado"),
                ),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=False, verbose_name="Requiere aprobación"
                    ),
                ),
                (
                    "allow_children",
                    models.BooleanField(default=True, verbose_name="Permite niños"),
                ),
                (
                    "minimum_age",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Edad mínima"
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(
                        upload_to="tours/main/", verbose_name="Imagen principal"
                    ),
                ),
                (
                    "gallery",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Galería de imágenes"
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Título SEO"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(blank=True, verbose_name="Descripción SEO"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tour",
                "verbose_name_plural": "Tours",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TourCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="Ícono"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#007bff", max_length=7, verbose_name="Color"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("sort_order", models.IntegerField(default=0, verbose_name="Orden")),
                (
                    "featured",
                    models.BooleanField(default=False, verbose_name="Destacado"),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Título SEO"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(blank=True, verbose_name="Descripción SEO"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Categoría de tour",
                "verbose_name_plural": "Categorías de tours",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="TourGuide",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("lead_guide", "Guía principal"),
                            ("assistant_guide", "Guía asistente"),
                            ("specialist", "Especialista"),
                            ("photographer", "Fotógrafo"),
                            ("logistics", "Logística"),
                        ],
                        max_length=50,
                        verbose_name="Rol",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Guía principal"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Guía de tour",
                "verbose_name_plural": "Guías de tours",
            },
        ),
        migrations.CreateModel(
            name="TourReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "overall_rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Calificación general",
                    ),
                ),
                (
                    "guide_rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Calificación del guía",
                    ),
                ),
                (
                    "accommodation_rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Calificación del alojamiento",
                    ),
                ),
                (
                    "food_rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Calificación de la comida",
                    ),
                ),
                (
                    "transportation_rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Calificación del transporte",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, verbose_name="Título"),
                ),
                ("comment", models.TextField(verbose_name="Comentario")),
                (
                    "pros",
                    models.TextField(blank=True, verbose_name="Aspectos positivos"),
                ),
                (
                    "cons",
                    models.TextField(blank=True, verbose_name="Aspectos negativos"),
                ),
                ("tips", models.TextField(blank=True, verbose_name="Consejos")),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Verificado"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Destacado"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("published", "Publicado"),
                            ("pending", "Pendiente"),
                            ("rejected", "Rechazado"),
                            ("hidden", "Oculto"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "photos",
                    models.JSONField(blank=True, default=list, verbose_name="Fotos"),
                ),
                (
                    "videos",
                    models.JSONField(blank=True, default=list, verbose_name="Videos"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Reseña de tour",
                "verbose_name_plural": "Reseñas de tours",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TourSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("departure_date", models.DateField(verbose_name="Fecha de salida")),
                ("return_date", models.DateField(verbose_name="Fecha de regreso")),
                (
                    "departure_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Hora de salida"
                    ),
                ),
                (
                    "meeting_point",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Punto de encuentro"
                    ),
                ),
                (
                    "max_participants",
                    models.IntegerField(verbose_name="Máximo de participantes"),
                ),
                (
                    "available_spots",
                    models.IntegerField(verbose_name="Cupos disponibles"),
                ),
                (
                    "waitlist_available",
                    models.BooleanField(default=True, verbose_name="Lista de espera"),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Precio",
                    ),
                ),
                (
                    "early_bird_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Descuento early bird",
                    ),
                ),
                (
                    "last_minute_surcharge",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Recargo last minute",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Disponible"),
                            ("full", "Completo"),
                            ("cancelled", "Cancelado"),
                            ("postponed", "Pospuesto"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "special_conditions",
                    models.TextField(blank=True, verbose_name="Condiciones especiales"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Horario de tour",
                "verbose_name_plural": "Horarios de tours",
                "ordering": ["departure_date", "departure_time"],
            },
        ),
    ]
