# Generated by Django 5.2.7 on 2025-10-10 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("staff", "0002_initial"),
        ("tours", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tour",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_tours",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_tours",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tourcategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="tours.tourcategory",
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tours",
                to="tours.tourcategory",
            ),
        ),
        migrations.AddField(
            model_name="tourguide",
            name="guide",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_tours",
                to="staff.staff",
            ),
        ),
        migrations.AddField(
            model_name="tourguide",
            name="tour",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_guides",
                to="tours.tour",
            ),
        ),
        migrations.AddField(
            model_name="tourreview",
            name="tour",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="tours.tour",
            ),
        ),
        migrations.AddField(
            model_name="tourreview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tour_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tourschedule",
            name="tour",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="tours.tour",
            ),
        ),
        migrations.AddField(
            model_name="tourreview",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="tours.tourschedule",
            ),
        ),
        migrations.AddIndex(
            model_name="tour",
            index=models.Index(
                fields=["status", "start_date"], name="tours_tour_status_f8a189_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tour",
            index=models.Index(
                fields=["category", "status"], name="tours_tour_categor_063e3a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tour",
            index=models.Index(
                fields=["is_featured", "status"], name="tours_tour_is_feat_0ba911_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tourguide",
            unique_together={("tour", "guide", "role")},
        ),
        migrations.AlterUniqueTogether(
            name="tourschedule",
            unique_together={("tour", "departure_date")},
        ),
        migrations.AlterUniqueTogether(
            name="tourreview",
            unique_together={("tour", "user", "schedule")},
        ),
    ]
