# Generated by Django 5.2.7 on 2025-10-10 18:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentCommission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "commission_type",
                    models.CharField(
                        choices=[
                            ("community", "Comunidad"),
                            ("guide", "Guía"),
                            ("agency", "Agencia"),
                            ("platform", "Plataforma"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de comisión",
                    ),
                ),
                (
                    "base_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Monto base"
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Tasa de comisión"
                    ),
                ),
                (
                    "commission_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Monto de comisión",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("calculated", "Calculada"),
                            ("pending", "Pendiente de pago"),
                            ("paid", "Pagada"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="calculated",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "paid_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de pago"
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Referencia de pago"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Comisión de pago",
                "verbose_name_plural": "Comisiones de pago",
            },
        ),
        migrations.CreateModel(
            name="PaymentInstallment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "installment_number",
                    models.IntegerField(verbose_name="Número de cuota"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Monto"
                    ),
                ),
                ("due_date", models.DateField(verbose_name="Fecha de vencimiento")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("paid", "Pagada"),
                            ("overdue", "Vencida"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "paid_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de pago"
                    ),
                ),
                (
                    "late_fee",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Mora"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cuota de pago",
                "verbose_name_plural": "Cuotas de pago",
                "ordering": ["installment_number"],
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Código"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("credit_card", "Tarjeta de crédito"),
                            ("debit_card", "Tarjeta de débito"),
                            ("bank_transfer", "Transferencia bancaria"),
                            ("paypal", "PayPal"),
                            ("cash", "Efectivo"),
                            ("other", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de método",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "is_online",
                    models.BooleanField(default=True, verbose_name="En línea"),
                ),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=False, verbose_name="Requiere aprobación"
                    ),
                ),
                (
                    "processing_time_hours",
                    models.IntegerField(
                        default=0, verbose_name="Tiempo de procesamiento (horas)"
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Monto mínimo",
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Monto máximo",
                    ),
                ),
                (
                    "fixed_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Tarifa fija",
                    ),
                ),
                (
                    "percentage_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Porcentaje de tarifa",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", max_length=3, verbose_name="Moneda"
                    ),
                ),
                (
                    "gateway_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Configuración de gateway",
                    ),
                ),
                (
                    "instructions",
                    models.TextField(blank=True, verbose_name="Instrucciones"),
                ),
                (
                    "supported_currencies",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Monedas soportadas"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Método de pago",
                "verbose_name_plural": "Métodos de pago",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PaymentPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "plan_name",
                    models.CharField(max_length=200, verbose_name="Nombre del plan"),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Monto total"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", max_length=3, verbose_name="Moneda"
                    ),
                ),
                (
                    "number_of_payments",
                    models.IntegerField(verbose_name="Número de pagos"),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("weekly", "Semanal"),
                            ("biweekly", "Quincenal"),
                            ("monthly", "Mensual"),
                            ("quarterly", "Trimestral"),
                        ],
                        max_length=20,
                        verbose_name="Frecuencia",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Fecha de inicio")),
                (
                    "next_payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Próxima fecha de pago"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activo"),
                            ("completed", "Completado"),
                            ("cancelled", "Cancelado"),
                            ("defaulted", "En mora"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "down_payment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Pago inicial",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Plan de pago",
                "verbose_name_plural": "Planes de pago",
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("charge", "Cargo"),
                            ("refund", "Reembolso"),
                            ("void", "Anulación"),
                            ("capture", "Captura"),
                            ("authorization", "Autorización"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de transacción",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Monto"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", max_length=3, verbose_name="Moneda"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("processing", "Procesando"),
                            ("completed", "Completado"),
                            ("failed", "Fallido"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "gateway_transaction_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="ID de transacción gateway",
                    ),
                ),
                (
                    "gateway_response",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Respuesta del gateway"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de procesamiento"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Metadatos"
                    ),
                ),
            ],
            options={
                "verbose_name": "Transacción de pago",
                "verbose_name_plural": "Transacciones de pago",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentWebhook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "webhook_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="ID del webhook"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(max_length=50, verbose_name="Tipo de evento"),
                ),
                ("source", models.CharField(max_length=50, verbose_name="Fuente")),
                ("payload", models.JSONField(verbose_name="Payload")),
                (
                    "signature",
                    models.CharField(blank=True, max_length=200, verbose_name="Firma"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Recibido"),
                            ("processing", "Procesando"),
                            ("processed", "Procesado"),
                            ("failed", "Fallido"),
                            ("ignored", "Ignorado"),
                        ],
                        default="received",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de procesamiento"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Mensaje de error"),
                ),
                (
                    "retry_count",
                    models.IntegerField(default=0, verbose_name="Número de reintentos"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Webhook de pago",
                "verbose_name_plural": "Webhooks de pago",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "refund_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Número de reembolso"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Monto"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", max_length=3, verbose_name="Moneda"
                    ),
                ),
                ("reason", models.TextField(verbose_name="Razón del reembolso")),
                (
                    "reason_code",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Código de razón"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Solicitado"),
                            ("processing", "Procesando"),
                            ("completed", "Completado"),
                            ("failed", "Fallido"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="requested",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de procesamiento"
                    ),
                ),
                (
                    "gateway_refund_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="ID de reembolso gateway",
                    ),
                ),
                (
                    "gateway_response",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Respuesta del gateway"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "customer_notified",
                    models.BooleanField(
                        default=False, verbose_name="Cliente notificado"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Reembolso",
                "verbose_name_plural": "Reembolsos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "payment_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Número de pago"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Monto"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", max_length=3, verbose_name="Moneda"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("processing", "Procesando"),
                            ("completed", "Completado"),
                            ("failed", "Fallido"),
                            ("cancelled", "Cancelado"),
                            ("refunded", "Reembolsado"),
                            ("partially_refunded", "Parcialmente reembolsado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "gateway_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Gateway de pago"
                    ),
                ),
                (
                    "gateway_transaction_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="ID de transacción gateway",
                    ),
                ),
                (
                    "gateway_response",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Respuesta del gateway"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de procesamiento"
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de vencimiento"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas internas")),
                (
                    "failure_reason",
                    models.TextField(blank=True, verbose_name="Razón de fallo"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Dirección IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, verbose_name="Agente de usuario"),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_payments",
                        to="bookings.booking",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago",
                "verbose_name_plural": "Pagos",
                "ordering": ["-created_at"],
            },
        ),
    ]
