# Generated by Django 5.2.7 on 2025-10-10 18:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StaffAttendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(verbose_name="Fecha")),
                (
                    "check_in_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Hora de entrada"
                    ),
                ),
                (
                    "check_out_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Hora de salida"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Presente"),
                            ("absent", "Ausente"),
                            ("late", "Tarde"),
                            ("half_day", "Medio día"),
                            ("vacation", "Vacaciones"),
                            ("sick", "Enfermo"),
                            ("personal_leave", "Licencia personal"),
                        ],
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Ubicación"
                    ),
                ),
                (
                    "is_auto_generated",
                    models.BooleanField(
                        default=False, verbose_name="Generado automáticamente"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Registro de asistencia",
                "verbose_name_plural": "Registros de asistencia",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="StaffPerformance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "review_period_start",
                    models.DateField(verbose_name="Inicio del período"),
                ),
                ("review_period_end", models.DateField(verbose_name="Fin del período")),
                (
                    "review_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de evaluación"
                    ),
                ),
                (
                    "review_type",
                    models.CharField(
                        choices=[
                            ("annual", "Anual"),
                            ("quarterly", "Trimestral"),
                            ("project_based", "Por proyecto"),
                            ("incident_based", "Por incidente"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de evaluación",
                    ),
                ),
                (
                    "overall_rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        verbose_name="Calificación general",
                    ),
                ),
                (
                    "punctuality_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        null=True,
                        verbose_name="Puntuación de puntualidad",
                    ),
                ),
                (
                    "customer_service_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        null=True,
                        verbose_name="Servicio al cliente",
                    ),
                ),
                (
                    "teamwork_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        null=True,
                        verbose_name="Trabajo en equipo",
                    ),
                ),
                (
                    "knowledge_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        null=True,
                        verbose_name="Conocimiento",
                    ),
                ),
                ("strengths", models.TextField(blank=True, verbose_name="Fortalezas")),
                (
                    "areas_for_improvement",
                    models.TextField(blank=True, verbose_name="Áreas de mejora"),
                ),
                ("goals", models.TextField(blank=True, verbose_name="Objetivos")),
                (
                    "manager_comments",
                    models.TextField(
                        blank=True, verbose_name="Comentarios del gerente"
                    ),
                ),
                (
                    "employee_comments",
                    models.TextField(
                        blank=True, verbose_name="Comentarios del empleado"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("in_review", "En revisión"),
                            ("completed", "Completada"),
                            ("acknowledged", "Reconocida"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "salary_adjustment",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Ajuste salarial",
                    ),
                ),
                (
                    "promotion_recommendation",
                    models.BooleanField(
                        default=False, verbose_name="Recomendación de promoción"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Evaluación de desempeño",
                "verbose_name_plural": "Evaluaciones de desempeño",
            },
        ),
        migrations.CreateModel(
            name="StaffRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre del rol"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "level",
                    models.IntegerField(
                        default=1,
                        help_text="1 = más bajo, 10 = más alto",
                        verbose_name="Nivel",
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(blank=True, default=dict, verbose_name="Permisos"),
                ),
                (
                    "can_manage_users",
                    models.BooleanField(
                        default=False, verbose_name="Puede gestionar usuarios"
                    ),
                ),
                (
                    "can_manage_bookings",
                    models.BooleanField(
                        default=False, verbose_name="Puede gestionar reservas"
                    ),
                ),
                (
                    "can_manage_tours",
                    models.BooleanField(
                        default=False, verbose_name="Puede gestionar tours"
                    ),
                ),
                (
                    "can_manage_staff",
                    models.BooleanField(
                        default=False, verbose_name="Puede gestionar personal"
                    ),
                ),
                (
                    "can_manage_communities",
                    models.BooleanField(
                        default=False, verbose_name="Puede gestionar comunidades"
                    ),
                ),
                (
                    "can_manage_content",
                    models.BooleanField(
                        default=False, verbose_name="Puede gestionar contenido"
                    ),
                ),
                (
                    "can_view_reports",
                    models.BooleanField(
                        default=False, verbose_name="Puede ver reportes"
                    ),
                ),
                (
                    "can_manage_finances",
                    models.BooleanField(
                        default=False, verbose_name="Puede gestionar finanzas"
                    ),
                ),
                (
                    "max_discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        max_digits=5,
                        verbose_name="Máximo descuento (%)",
                    ),
                ),
                (
                    "can_approve_bookings",
                    models.BooleanField(
                        default=False, verbose_name="Puede aprobar reservas"
                    ),
                ),
                (
                    "can_cancel_bookings",
                    models.BooleanField(
                        default=False, verbose_name="Puede cancelar reservas"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Rol de empleado",
                "verbose_name_plural": "Roles de empleados",
                "ordering": ["level", "name"],
            },
        ),
        migrations.CreateModel(
            name="StaffRoleAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "assigned_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de asignación"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de inicio"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de fin"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
            ],
            options={
                "verbose_name": "Asignación de rol",
                "verbose_name_plural": "Asignaciones de roles",
            },
        ),
        migrations.CreateModel(
            name="StaffSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("regular", "Regular"),
                            ("tour_assignment", "Asignación a tour"),
                            ("vacation", "Vacaciones"),
                            ("sick_leave", "Licencia médica"),
                            ("personal_leave", "Licencia personal"),
                            ("training", "Entrenamiento"),
                            ("overtime", "Tiempo extra"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de horario",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Fecha de inicio")),
                ("end_date", models.DateField(verbose_name="Fecha de fin")),
                (
                    "start_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Hora de inicio"
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="Hora de fin"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Programado"),
                            ("confirmed", "Confirmado"),
                            ("in_progress", "En progreso"),
                            ("completed", "Completado"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Ubicación"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Horario de empleado",
                "verbose_name_plural": "Horarios de empleados",
            },
        ),
        migrations.CreateModel(
            name="StaffTraining",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="Título del entrenamiento"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "training_type",
                    models.CharField(
                        choices=[
                            ("certification", "Certificación"),
                            ("workshop", "Taller"),
                            ("course", "Curso"),
                            ("seminar", "Seminario"),
                            ("on_the_job", "En el trabajo"),
                            ("other", "Otro"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de entrenamiento",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Proveedor"
                    ),
                ),
                (
                    "instructor",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Instructor"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Fecha de inicio")),
                ("end_date", models.DateField(verbose_name="Fecha de fin")),
                (
                    "completion_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de completación"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Programado"),
                            ("in_progress", "En progreso"),
                            ("completed", "Completado"),
                            ("cancelled", "Cancelado"),
                            ("expired", "Expirado"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Número de certificado"
                    ),
                ),
                (
                    "certificate_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="staff/certificates/",
                        verbose_name="Archivo de certificado",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de expiración"
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Costo",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Ubicación"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Entrenamiento de empleado",
                "verbose_name_plural": "Entrenamientos de empleados",
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="ID de empleado"
                    ),
                ),
                ("hire_date", models.DateField(verbose_name="Fecha de contratación")),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de nacimiento"
                    ),
                ),
                (
                    "personal_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email personal"
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Contacto de emergencia",
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono de emergencia"
                    ),
                ),
                (
                    "emergency_contact_relationship",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Relación"
                    ),
                ),
                ("position", models.CharField(max_length=100, verbose_name="Posición")),
                (
                    "department",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Departamento"
                    ),
                ),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("active", "Activo"),
                            ("inactive", "Inactivo"),
                            ("on_leave", "De licencia"),
                            ("terminated", "Terminado"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Estado laboral",
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Tiempo completo"),
                            ("part_time", "Medio tiempo"),
                            ("contractor", "Contratista"),
                            ("seasonal", "Temporal"),
                        ],
                        default="full_time",
                        max_length=20,
                        verbose_name="Tipo de empleo",
                    ),
                ),
                (
                    "salary_info",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Información salarial"
                    ),
                ),
                (
                    "work_location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Ubicación de trabajo"
                    ),
                ),
                (
                    "is_remote",
                    models.BooleanField(default=False, verbose_name="Trabajo remoto"),
                ),
                (
                    "work_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono laboral"
                    ),
                ),
                (
                    "work_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email laboral"
                    ),
                ),
                (
                    "contract_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="staff/contracts/",
                        verbose_name="Archivo de contrato",
                    ),
                ),
                (
                    "id_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="staff/ids/",
                        verbose_name="Documento de identidad",
                    ),
                ),
                (
                    "certifications",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Certificaciones"
                    ),
                ),
                (
                    "bio",
                    models.TextField(blank=True, verbose_name="Biografía profesional"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="staff/photos/",
                        verbose_name="Foto profesional",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas internas")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subordinates",
                        to="staff.staff",
                    ),
                ),
            ],
            options={
                "verbose_name": "Empleado",
                "verbose_name_plural": "Empleados",
                "ordering": ["user__first_name", "user__last_name"],
            },
        ),
    ]
