# Generated by Django 5.2.7 on 2025-10-10 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("staff", "0001_initial"),
        ("tours", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="staffattendance",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="staff.staff",
            ),
        ),
        migrations.AddField(
            model_name="staffperformance",
            name="reviewed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="performance_reviews_made",
                to="staff.staff",
            ),
        ),
        migrations.AddField(
            model_name="staffperformance",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="performance_reviews",
                to="staff.staff",
            ),
        ),
        migrations.AddField(
            model_name="staffroleassignment",
            name="assigned_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="role_assignments_made",
                to="staff.staff",
            ),
        ),
        migrations.AddField(
            model_name="staffroleassignment",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="staff.staffrole",
            ),
        ),
        migrations.AddField(
            model_name="staffroleassignment",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_assignments",
                to="staff.staff",
            ),
        ),
        migrations.AddField(
            model_name="staffschedule",
            name="assigned_tour",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_assignments",
                to="tours.tour",
            ),
        ),
        migrations.AddField(
            model_name="staffschedule",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="staff.staff",
            ),
        ),
        migrations.AddField(
            model_name="stafftraining",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trainings",
                to="staff.staff",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="staffattendance",
            unique_together={("staff", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="staffroleassignment",
            unique_together={("staff", "role", "is_active")},
        ),
    ]
