# Generated by Django 5.2.7 on 2025-10-10 18:13

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono"
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de nacimiento"
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nacionalidad"
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Contacto de emergencia",
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono de emergencia"
                    ),
                ),
                (
                    "medical_conditions",
                    models.TextField(blank=True, verbose_name="Condiciones médicas"),
                ),
                (
                    "dietary_restrictions",
                    models.TextField(
                        blank=True, verbose_name="Restricciones alimentarias"
                    ),
                ),
                (
                    "preferred_activities",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Actividades preferidas"
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("beginner", "Principiante"),
                            ("intermediate", "Intermedio"),
                            ("advanced", "Avanzado"),
                            ("expert", "Experto"),
                        ],
                        max_length=20,
                        verbose_name="Nivel de experiencia",
                    ),
                ),
                (
                    "languages_spoken",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Idiomas hablados"
                    ),
                ),
                (
                    "profile_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Público"),
                            ("friends", "Solo contactos"),
                            ("private", "Privado"),
                        ],
                        default="public",
                        max_length=20,
                        verbose_name="Visibilidad del perfil",
                    ),
                ),
                (
                    "loyalty_points",
                    models.IntegerField(default=0, verbose_name="Puntos de fidelidad"),
                ),
                (
                    "total_trips",
                    models.IntegerField(default=0, verbose_name="Total de viajes"),
                ),
                (
                    "member_since",
                    models.DateField(auto_now_add=True, verbose_name="Miembro desde"),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True, verbose_name="Notificaciones por email"
                    ),
                ),
                (
                    "sms_notifications",
                    models.BooleanField(
                        default=False, verbose_name="Notificaciones por SMS"
                    ),
                ),
                (
                    "marketing_emails",
                    models.BooleanField(
                        default=True, verbose_name="Emails de marketing"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "ordering": ["-created_at"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("login", "Inicio de sesión"),
                            ("booking", "Reserva realizada"),
                            ("review", "Reseña publicada"),
                            ("profile_update", "Perfil actualizado"),
                            ("password_change", "Contraseña cambiada"),
                            ("payment", "Pago realizado"),
                            ("cancellation", "Cancelación"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de actividad",
                    ),
                ),
                ("description", models.TextField(verbose_name="Descripción")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Metadatos"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Dirección IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, verbose_name="Agente de usuario"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Actividad de usuario",
                "verbose_name_plural": "Actividades de usuario",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        default="es", max_length=10, verbose_name="Idioma preferido"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="America/Guayaquil",
                        max_length=50,
                        verbose_name="Zona horaria",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", max_length=3, verbose_name="Moneda preferida"
                    ),
                ),
                (
                    "booking_reminders",
                    models.BooleanField(
                        default=True, verbose_name="Recordatorios de reserva"
                    ),
                ),
                (
                    "promotional_emails",
                    models.BooleanField(
                        default=True, verbose_name="Emails promocionales"
                    ),
                ),
                (
                    "sms_updates",
                    models.BooleanField(
                        default=False, verbose_name="Actualizaciones por SMS"
                    ),
                ),
                (
                    "push_notifications",
                    models.BooleanField(
                        default=True, verbose_name="Notificaciones push"
                    ),
                ),
                (
                    "share_booking_history",
                    models.BooleanField(
                        default=False, verbose_name="Compartir historial de reservas"
                    ),
                ),
                (
                    "allow_marketing_contact",
                    models.BooleanField(
                        default=True, verbose_name="Permitir contacto de marketing"
                    ),
                ),
                (
                    "data_collection_consent",
                    models.BooleanField(
                        default=True,
                        verbose_name="Consentimiento de recopilación de datos",
                    ),
                ),
                (
                    "high_contrast",
                    models.BooleanField(default=False, verbose_name="Alto contraste"),
                ),
                (
                    "large_text",
                    models.BooleanField(default=False, verbose_name="Texto grande"),
                ),
                (
                    "reduced_motion",
                    models.BooleanField(
                        default=False, verbose_name="Movimiento reducido"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Preferencia de usuario",
                "verbose_name_plural": "Preferencias de usuario",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Biografía")),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/",
                        verbose_name="Avatar",
                    ),
                ),
                (
                    "cover_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="covers/",
                        verbose_name="Foto de portada",
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Dirección")),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Ciudad"),
                ),
                (
                    "country",
                    models.CharField(blank=True, max_length=100, verbose_name="País"),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Código postal"
                    ),
                ),
                (
                    "occupation",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Ocupación"
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Empresa"
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="Sitio web")),
                ("facebook", models.URLField(blank=True, verbose_name="Facebook")),
                ("instagram", models.URLField(blank=True, verbose_name="Instagram")),
                ("twitter", models.URLField(blank=True, verbose_name="Twitter")),
                ("linkedin", models.URLField(blank=True, verbose_name="LinkedIn")),
                (
                    "travel_style",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Estilo de viaje"
                    ),
                ),
                (
                    "budget_preference",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("budget", "Económico"),
                            ("comfort", "Confort"),
                            ("luxury", "Lujo"),
                        ],
                        max_length=20,
                        verbose_name="Presupuesto preferido",
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        blank=True, max_length=5, verbose_name="Tipo de sangre"
                    ),
                ),
                ("allergies", models.TextField(blank=True, verbose_name="Alergias")),
                (
                    "medications",
                    models.TextField(blank=True, verbose_name="Medicamentos"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de usuario",
                "verbose_name_plural": "Perfiles de usuario",
            },
        ),
    ]
