# Generated by Django 5.2.7 on 2025-10-10 18:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Community",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                ("description", models.TextField(verbose_name="Descripción")),
                (
                    "contact_person",
                    models.CharField(
                        max_length=200, verbose_name="Persona de contacto"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email de contacto"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Teléfono")),
                ("address", models.TextField(blank=True, verbose_name="Dirección")),
                (
                    "province",
                    models.CharField(max_length=100, verbose_name="Provincia"),
                ),
                ("canton", models.CharField(max_length=100, verbose_name="Cantón")),
                ("parish", models.CharField(max_length=100, verbose_name="Parroquia")),
                (
                    "coordinates",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Coordenadas GPS"
                    ),
                ),
                (
                    "population",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Población aproximada"
                    ),
                ),
                (
                    "families",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Número de familias"
                    ),
                ),
                (
                    "main_activities",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Actividades principales"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activa"),
                            ("inactive", "Inactiva"),
                            ("suspended", "Suspendida"),
                            ("in_formation", "En formación"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Verificada"),
                ),
                (
                    "verification_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de verificación"
                    ),
                ),
                (
                    "main_income_sources",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="Fuentes de ingresos principales",
                    ),
                ),
                (
                    "tourism_impact",
                    models.TextField(blank=True, verbose_name="Impacto del turismo"),
                ),
                (
                    "development_needs",
                    models.TextField(
                        blank=True, verbose_name="Necesidades de desarrollo"
                    ),
                ),
                (
                    "legal_representative",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Representante legal"
                    ),
                ),
                (
                    "legal_id",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Cédula/RUC"
                    ),
                ),
                (
                    "legal_documents",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Documentos legales"
                    ),
                ),
                (
                    "max_tourists_per_day",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Máximo de turistas por día"
                    ),
                ),
                (
                    "visiting_hours",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Horarios de visita"
                    ),
                ),
                (
                    "languages_spoken",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Idiomas hablados"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="communities/logos/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "photos",
                    models.JSONField(blank=True, default=list, verbose_name="Fotos"),
                ),
                (
                    "documents",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Documentos"
                    ),
                ),
                (
                    "total_tours_hosted",
                    models.IntegerField(
                        default=0, verbose_name="Total de tours recibidos"
                    ),
                ),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Ingresos totales",
                    ),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                        verbose_name="Calificación promedio",
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=15.0,
                        max_digits=5,
                        verbose_name="Tasa de comisión",
                    ),
                ),
                (
                    "payment_terms",
                    models.TextField(blank=True, verbose_name="Términos de pago"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Comunidad",
                "verbose_name_plural": "Comunidades",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CommunityBooking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "client_name",
                    models.CharField(max_length=200, verbose_name="Nombre del cliente"),
                ),
                (
                    "client_email",
                    models.EmailField(max_length=254, verbose_name="Email del cliente"),
                ),
                (
                    "client_phone",
                    models.CharField(
                        max_length=20, verbose_name="Teléfono del cliente"
                    ),
                ),
                (
                    "number_of_participants",
                    models.IntegerField(verbose_name="Número de participantes"),
                ),
                ("booking_date", models.DateField(verbose_name="Fecha de la reserva")),
                (
                    "start_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Hora de inicio"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Monto total"
                    ),
                ),
                (
                    "commission_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Monto de comisión",
                    ),
                ),
                (
                    "community_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Monto para comunidad",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("confirmed", "Confirmada"),
                            ("completed", "Completada"),
                            ("cancelled", "Cancelada"),
                            ("no_show", "No presentado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "special_requests",
                    models.TextField(blank=True, verbose_name="Solicitudes especiales"),
                ),
                (
                    "internal_notes",
                    models.TextField(blank=True, verbose_name="Notas internas"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Reserva comunitaria",
                "verbose_name_plural": "Reservas comunitarias",
            },
        ),
        migrations.CreateModel(
            name="CommunityFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "visitor_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nombre del visitante"
                    ),
                ),
                (
                    "visitor_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email del visitante"
                    ),
                ),
                (
                    "overall_rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        verbose_name="Calificación general",
                    ),
                ),
                (
                    "service_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        null=True,
                        verbose_name="Calificación del servicio",
                    ),
                ),
                (
                    "guide_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        null=True,
                        verbose_name="Calificación del guía",
                    ),
                ),
                (
                    "value_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        null=True,
                        verbose_name="Calificación de valor",
                    ),
                ),
                ("comment", models.TextField(verbose_name="Comentario")),
                (
                    "positives",
                    models.TextField(blank=True, verbose_name="Aspectos positivos"),
                ),
                (
                    "improvements",
                    models.TextField(blank=True, verbose_name="Mejoras sugeridas"),
                ),
                (
                    "would_recommend",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Recomendaría"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, verbose_name="Comentario público"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Verificado"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Feedback comunitario",
                "verbose_name_plural": "Feedback comunitarios",
            },
        ),
        migrations.CreateModel(
            name="CommunityMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Apellido"),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de nacimiento"
                    ),
                ),
                (
                    "gender",
                    models.CharField(blank=True, max_length=20, verbose_name="Género"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("address", models.TextField(blank=True, verbose_name="Dirección")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("leader", "Líder"),
                            ("elder", "Anciano"),
                            ("guide", "Guía"),
                            ("artisan", "Artesano"),
                            ("cook", "Cocinero"),
                            ("member", "Miembro"),
                            ("other", "Otro"),
                        ],
                        max_length=50,
                        verbose_name="Rol",
                    ),
                ),
                (
                    "special_skills",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Habilidades especiales"
                    ),
                ),
                (
                    "languages_spoken",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Idiomas hablados"
                    ),
                ),
                (
                    "certifications",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Certificaciones"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "can_guide_tours",
                    models.BooleanField(
                        default=False, verbose_name="Puede guiar tours"
                    ),
                ),
                (
                    "can_host_visitors",
                    models.BooleanField(
                        default=False, verbose_name="Puede hospedar visitantes"
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Biografía")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="community_members/",
                        verbose_name="Foto",
                    ),
                ),
                (
                    "emergency_contact",
                    models.TextField(blank=True, verbose_name="Contacto de emergencia"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Miembro de comunidad",
                "verbose_name_plural": "Miembros de comunidad",
            },
        ),
        migrations.CreateModel(
            name="CommunityService",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del servicio"
                    ),
                ),
                ("description", models.TextField(verbose_name="Descripción")),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("accommodation", "Alojamiento"),
                            ("food", "Alimentación"),
                            ("guide", "Guía local"),
                            ("crafts", "Artesanías"),
                            ("cultural_show", "Espectáculo cultural"),
                            ("workshop", "Taller"),
                            ("transport", "Transporte"),
                            ("other", "Otro"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de servicio",
                    ),
                ),
                ("max_capacity", models.IntegerField(verbose_name="Capacidad máxima")),
                (
                    "min_notice_hours",
                    models.IntegerField(
                        default=24, verbose_name="Horas mínimas de anticipación"
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio base"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", max_length=3, verbose_name="Moneda"
                    ),
                ),
                (
                    "pricing_model",
                    models.CharField(
                        choices=[
                            ("per_person", "Por persona"),
                            ("per_group", "Por grupo"),
                            ("per_hour", "Por hora"),
                            ("per_day", "Por día"),
                        ],
                        max_length=20,
                        verbose_name="Modelo de precios",
                    ),
                ),
                (
                    "available_days",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Días disponibles"
                    ),
                ),
                (
                    "available_hours",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Horarios disponibles"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=False, verbose_name="Requiere aprobación"
                    ),
                ),
                (
                    "requirements",
                    models.TextField(blank=True, verbose_name="Requisitos"),
                ),
                (
                    "included_items",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Items incluidos"
                    ),
                ),
                (
                    "recommendations",
                    models.TextField(blank=True, verbose_name="Recomendaciones"),
                ),
                (
                    "photos",
                    models.JSONField(blank=True, default=list, verbose_name="Fotos"),
                ),
                (
                    "videos",
                    models.JSONField(blank=True, default=list, verbose_name="Videos"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Servicio comunitario",
                "verbose_name_plural": "Servicios comunitarios",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CommunityTour",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("description", models.TextField(verbose_name="Descripción")),
                (
                    "duration_hours",
                    models.IntegerField(verbose_name="Duración en horas"),
                ),
                (
                    "itinerary",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Itinerario"
                    ),
                ),
                (
                    "activities",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Actividades"
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("easy", "Fácil"),
                            ("moderate", "Moderado"),
                            ("challenging", "Desafiante"),
                        ],
                        max_length=20,
                        verbose_name="Nivel de dificultad",
                    ),
                ),
                (
                    "price_per_person",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Precio por persona",
                    ),
                ),
                (
                    "min_participants",
                    models.IntegerField(
                        default=2, verbose_name="Mínimo de participantes"
                    ),
                ),
                (
                    "max_participants",
                    models.IntegerField(verbose_name="Máximo de participantes"),
                ),
                (
                    "available_days",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Días disponibles"
                    ),
                ),
                (
                    "available_months",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Meses disponibles"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Destacado"),
                ),
                (
                    "photos",
                    models.JSONField(blank=True, default=list, verbose_name="Fotos"),
                ),
                (
                    "videos",
                    models.JSONField(blank=True, default=list, verbose_name="Videos"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tour comunitario",
                "verbose_name_plural": "Tours comunitarios",
            },
        ),
    ]
