# Generated by Django 5.2.7 on 2025-10-10 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("communities", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_communities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_communities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="communitybooking",
            name="community",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="communities.community",
            ),
        ),
        migrations.AddField(
            model_name="communityfeedback",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback",
                to="communities.communitybooking",
            ),
        ),
        migrations.AddField(
            model_name="communityfeedback",
            name="community",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback",
                to="communities.community",
            ),
        ),
        migrations.AddField(
            model_name="communitymember",
            name="community",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="communities.community",
            ),
        ),
        migrations.AddField(
            model_name="communityservice",
            name="community",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="communities.community",
            ),
        ),
        migrations.AddField(
            model_name="communitybooking",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="communities.communityservice",
            ),
        ),
        migrations.AddField(
            model_name="communitytour",
            name="community",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tours",
                to="communities.community",
            ),
        ),
        migrations.AddField(
            model_name="communitybooking",
            name="tour",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="communities.communitytour",
            ),
        ),
        migrations.AddIndex(
            model_name="community",
            index=models.Index(
                fields=["status", "province"], name="communities_status_75dbe6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="community",
            index=models.Index(
                fields=["is_verified", "status"], name="communities_is_veri_e193ca_idx"
            ),
        ),
    ]
